apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    type: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    type: demo-voting-app